DROP TABLE IF EXISTS COUNTRY;

  CREATE TABLE COUNTRY (
    CODE VARCHAR(2) NOT NULL,
    NAME VARCHAR(100) NULL,
    CURRENCY VARCHAR(100) NULL,
    CURRENCY_SYMBOL VARCHAR(100) NULL,
    LANGUAGE VARCHAR(100) NULL,
    CAPITAL VARCHAR(100) NULL,
    CONSTRAINT CODE_PK PRIMARY KEY (CODE)
  );