apiVersion: v1
kind: Service
metadata:
  name: countries-service
  namespace: {{ .Values.nameSpace }}
spec:
  type: NodePort
  selector:
    app: countries-service-pod
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 32000