apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitals-service-app
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    matchLabels:
      app: capitals-service-pod
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: capitals-service-pod
        owner: alehrekuts
    spec:
      containers:
        - name: capitals-service
          image: barmaleus/capitals-service:1.2.0
          ports:
            - containerPort: 8100
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: capitals-configmap
                  key: spring_application_name
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: capitals-configmap
                  key: server_port
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: capitals-configmap
                  key: management_endpoint_health_probes_enabled
            - name: COUNTRIESSERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: capitals-configmap
                  key: countriesservice_port
            - name: NODE_IP
              valueFrom:
                configMapKeyRef:
                  name: capitals-configmap
                  key: node_ip
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8100
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8100
            failureThreshold: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8100
            failureThreshold: 1
            periodSeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1