apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: k8s-program
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pgdata"
