apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: countries-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: countries-service-pod
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 32000

---

apiVersion: v1
kind: Service
metadata:
  name: capitals-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: capitals-service-pod
  ports:
    - protocol: "TCP"
      port: 8100
      nodePort: 32100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: countries-service-app
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: countries-service-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: countries-service-pod
        owner: alehrekuts
    spec:
      containers:
        - name: countries-service
          image: barmaleus/countries-service:1.1.0
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_APPLICATION_NAME
              value: countries-service
            - name: SERVER_PORT
              value: "8000"
            - name: SPRING_JPA_SHOWSQL
              value: "true"
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "true"
            - name: SPRING_JPA_HIBERNATE_DDLAUTO
              value: none

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitals-service-app
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: capitals-service-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: capitals-service-pod
        owner: alehrekuts
    spec:
      containers:
        - name: capitals-service
          image: barmaleus/capitals-service:1.1.0
          ports:
            - containerPort: 8100
          env:
            - name: SPRING_APPLICATION_NAME
              value: capitals-service
            - name: SERVER_PORT
              value: "8100"
            - name: COUNTRIESSERVICE_PORT
              value: "8000"
            - name: NODE_IP
              value: 10.97.143.247
