apiVersion: v1
kind: PersistentVolume
metadata:
  name: countries-pv
  namespace: k8s-program
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/scripts"
