
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    matchLabels:
      app: postgres-db
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: postgres-db
        owner: alehrekuts
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:16.1.0
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_USERNAME
            - name: ALLOW_EMPTY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: allow_empty_password
          volumeMounts:
            - name: postgres-storage
              mountPath: /data/pgdata
            - name: sql-scripts
              mountPath: /docker-entrypoint-initdb.d
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -p 5432 -U countriesuser
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -p 5432 -U countriesuser
            failureThreshold: 1
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -p 5432 -U countriesuser
            failureThreshold: 1
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: sql-scripts
          configMap:
            name: sql-configmap
