apiVersion: v1
data:
  SPRING_DATASOURCE_PASSWORD: MTIzNDU2Nzg=
  SPRING_DATASOURCE_USERNAME: Y291bnRyaWVzdXNlcg==
kind: Secret
metadata:
  creationTimestamp: "2023-11-23T11:42:28Z"
  name: db-credentials
  namespace: k8s-program
  resourceVersion: "226000"
  uid: 1d0d1105-c11d-468f-b226-4cf986c01913
type: Opaque
