apiVersion: v1
kind: Service
metadata:
  name: postgres-statefulset
  namespace: k8s-program
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres-db
  ports:
    - protocol: "TCP"
      name: postgresql
      port: 5432
      targetPort: postgresql

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: k8s-program
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres-db
  ports:
    - protocol: "TCP"
      name: postgresql
      port: 5432
      targetPort: postgresql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: postgres-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
        owner: alehrekuts
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:16.1.0
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_USERNAME
            - name: ALLOW_EMPTY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: allow_empty_password
          volumeMounts:
            - name: postgres-storage
              mountPath: /data/pgdata
            - name: sql-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: sql-scripts
          configMap:
            name: sql-configmap
