apiVersion: v1
kind: Service
metadata:
  name: capitals-service
  namespace: {{ .Values.nameSpace }}
spec:
  type: ClusterIP
  selector:
    app: capitals-service-pod
  ports:
    - protocol: "TCP"
      port: 80